name: GitTesting
env:
  APPLICATION_NAME : "GitTesting"

on: [push]

jobs:
  run-tests:

    runs-on: [ubuntu-18.04]

    steps:
      - name: Java version
        run: java -version
      - name: Installing maven
        run: sudo apt-get -y install maven
      - name: Maven version
        run: mvn -version
      - name: Clone repository
        uses: actions/checkout@v1
      - name: check branch
        run: git branch
      - name: Run tests
        run: mvn test
