name: GitTesting
env:
  APPLICATION_NAME : "GitTesting"

on: [push]

jobs:
  run-tests:

    runs-on: [ubuntu-18.04]

    steps:
#      - name: Clone repository
#        uses: actions/checkout@v1
      - name: clone github-actions-testing
        uses: actions/checkout@v2
        with:
          repository: RooBarsic/git-test
      - name: ls -l
        run: ls -l
      - name: check branch
        run: git branch
      - name: check branch
        run: git branch
