name: GitTesting
env:
  GIT_DEFAULT_USER_NAME : "Github Actions"
  GIT_DEFAULT_USER_EMAIL : "actions_github@gmail.com"

  TARGET_BRANCH_NAME : "master"
  REPOSITORY_AND_OWNER_NAME : ${{ github.repository }}

on: [push]

jobs:
  run-tests:

    runs-on: [ubuntu-18.04]

    steps:
      - name: Presetting the working environment
        run: |
          sudo apt-get -y install maven
          java -version
          mvn -version
          git config --global user.name $GIT_DEFAULT_USER_NAME
          git config --global user.email $GIT_DEFAULT_USER_EMAIL      

      # Clonning necessary branches
      - name: Clone master branch
        run: git clone --branch master https://github.com/$REPOSITORY_AND_OWNER_NAME.git
      - name: Clone current branch to previously clonned master branch
        working-directory: ./${{ github.event.repository.name }}
        run: git fetch origin ${GITHUB_REF##*/}:${GITHUB_REF##*/}

      # Testing two branches independently
      - name: Run tests for current branch
        working-directory: ./${{ github.event.repository.name }}
        run: |
          git checkout ${GITHUB_REF##*/}
          mvn test
      - name: Run tests for master
        working-directory: ./${{ github.event.repository.name }}
        run: |
          git checkout $TARGET_BRANCH_NAME
          mvn test

      # Locally merging two branches
      - name: merge master with current branch
        working-directory: ./${{ github.event.repository.name }}
        run: git merge ${GITHUB_REF##*/}
      # Testing the result of merging
      - name: Run tests for merge result
        working-directory: ./${{ github.event.repository.name }}
        run: mvn test
